### ISSUE TITLE
Request: Add install instructions to README.md

### ISSUE THREAD

**Issue by kjkent** [fzakaria/nix-auto-follow#22]
Hey there,

This looks great, but I'm pretty new to Nix and have been wrapping my head around it for a few weeks now. Would it be possible to get some installation instructions added to the readme? FWIW I'm on a flake-based NixOS config. I see the flake.nix in this repo adds the package to nixpkgs' overlays, but I'm not sure how to best add that to my flake, as I suppose just adding to the inputs won't be sufficient.

Thanks so much

**Edit:** Hey, I just found out I can run `nix run github:fzakaria/nix-auto-follow` and it just works -- magic!

**Edit 2:** And I've just seen that the `nix run` command is _in the README_. Apologies; I was tired/am a fool.

**Comment by fzakaria** [comment]
Sorry I didn' tanswer; but I'm glad you have it figured out :)
